export interface Project {
    name: string
    repo: string
    description: string
    icon?: string
    homepage?: string
    tags?: string[]
    stars?: number
    featured?: boolean
}

export interface ProjectCategory {
    title: string
    icon: string
    projects: Project[]
}

export const projectCategories: ProjectCategory[] = [
    {
        title: '🔥 热门项目',
        icon: '⭐',
        projects: [
            {
                name: 'js-challenges',
                repo: 'Sunny-117/js-challenges',
                description: '✨✨✨ Challenge your JavaScript programming limits step by step 前端手写题，一步步提升 JavaScript 编程水平',
                icon: '💪',
                homepage: 'https://deepwiki.com/Sunny-117/js-challenges',
                stars: 2300,
                tags: ['Html-css-javascript', 'Javascript', 'Nodejs'],
                featured: true,
            },
            {
                name: 'tiny-anything',
                repo: 'Sunny-117/tiny-anything',
                description: '🚀 Explore the source code of the front-end library and implement a super mini version 前端轮子库，包含框架及其周边生态、工具链、插件迷你源码实现',
                icon: '📦',
                homepage: 'https://deepwiki.com/Sunny-117/tiny-anything',
                stars: 125,
                tags: ['Esbuild', 'Hooks', 'Pinia'],
                featured: true,
            },
            {
                name: 'BOSScript',
                repo: 'Sunny-117/BOSScript',
                description: 'boss直聘一键批量投递，一条龙服务的油猴脚本',
                icon: '🤖',
                stars: 85,
                tags: ['Boss', 'Resume', 'Script'],
                featured: true,
            },
            {
                name: 'blog',
                repo: 'Sunny-117/blog',
                description: '✨✨✨ 前端历险记',
                icon: '📝',
                homepage: 'https://sunny-117.github.io/blog/',
                stars: 44,
                featured: true,
            },
            {
                name: 'awesome-native',
                repo: 'Sunny-117/awesome-native',
                description: '🔧 Collection of native JavaScript projects',
                icon: '💎',
                stars: 33,
                tags: ['Css3', 'Html', 'Javascript'],
                featured: true,
            }
        ],
    },
    {
        title: '构建工具 & 工程化',
        icon: '🛠️',
        projects: [
            {
                name: 'tiny-vite',
                repo: 'Sunny-117/tiny-vite',
                description: '⚡️ a lightweight frontend build tool designed to deliver swift development experiences and efficient build processes。支持双引擎架构，esbuild 预构建，ModuleGraph，HMR，插件架构，单文件编译，代码压缩',
                icon: '⚡',
                homepage: 'https://deepwiki.com/Sunny-117/tiny-vite',
                stars: 14,
                tags: ['Bundle', 'Esbuild', 'Esbuild-plugin'],
            },
            {
                name: 'mini-vite',
                repo: 'Sunny-117/mini-vite',
                description: '下一代的前端工具链 Vite 核心逻辑',
                icon: '📦',
                stars: 8,
            },
            {
                name: 'esbuild-core-plugins',
                repo: 'Sunny-117/esbuild-core-plugins',
                description: '掘金专栏 esbuild 原理与应用实战 代码仓库 掘金专栏地址：https://juejin.cn/column/7285233095058718756',
                icon: '🔌',
                stars: 5,
                tags: ['Esbuild', 'Esbuild-node', 'Esbuild-plugin'],
            },
            {
                name: 'vite-plugin-react-devtools',
                repo: 'Sunny-117/vite-plugin-react-devtools',
                description: 'vite-plugin-react-devtools',
                icon: '🎮',
                stars: 5,
            },
            {
                name: 'robuild',
                repo: 'Sunny-117/robuild',
                description: '⚡️ Zero-config ESM/TS package builder. Powered by Oxc, Rolldown and rolldown-plugin-dts. 零配置 ESM/TS 包构建器 基于 Oxc、Rolldown 和 rolldown-plugin-dts 构建，专注于 ESM 兼容性和极速构建',
                icon: '🔧',
                homepage: 'https://sunny-117.github.io/robuild/',
                stars: 3,
                tags: ['Bundler', 'Esbuild', 'Lib'],
            },
            {
                name: 'tiny-webpack',
                repo: 'Sunny-117/tiny-webpack',
                description: '✨ A JavaScript bundler with Webpack-like features, supporting modern frontend workflows.',
                icon: '📦',
                stars: 3,
                tags: ['Code', 'Codesplitting', 'Dynamic-import'],
            },
            {
                name: 'bundle-go',
                repo: 'Sunny-117/bundle-go',
                description: '📦️ js packager by golang',
                icon: '🐹',
                stars: 2,
            },
            {
                name: 'vite-core-plugins',
                repo: 'Sunny-117/vite-core-plugins',
                description: 'Vite core and plugins',
                icon: '🔥',
                stars: 2,
                tags: ['Build-tool', 'Core', 'Plugins'],
            },
            {
                name: 'vite-plugin-ai-doctor',
                repo: 'Sunny-117/vite-plugin-ai-doctor',
                description: '🤖 AI-powered error diagnosis plugin for Vite builds | AI 驱动的 Vite 构建错误诊断插件',
                icon: '🔧',
                stars: 2,
                tags: ['Ai', 'Ai-doctor', 'Devtools'],
            },
            {
                name: 'create-rolldown',
                repo: 'Sunny-117/create-rolldown',
                description: '⚡️ Scaffolding tool for Rolldown library projects - a fast JavaScript bundler written in Rust.',
                icon: '🎨',
                homepage: 'https://rolldown.rs/',
                stars: 1,
                tags: ['Bundler', 'Cli', 'Create-app'],
            },
            {
                name: 'vite-plugin-oxc',
                repo: 'Sunny-117/vite-plugin-oxc',
                description: 'Oxc integration for vite.',
                icon: '💫',
                stars: 1,
            },
            {
                name: 'webassembly-bundler',
                repo: 'Sunny-117/webassembly-bundler',
                description: 'webassembly-bundler',
                icon: '✨',
                stars: 0,
            }
        ],
    },
    {
        title: 'React 生态',
        icon: '⚛️',
        projects: [
            {
                name: 'tiny-react',
                repo: 'Sunny-117/tiny-react',
                description: '🌱 The closest implementation to the React source code',
                icon: '🌱',
                stars: 8,
                tags: ['Framework', 'React'],
            },
            {
                name: 'rc-design',
                repo: 'Sunny-117/rc-design',
                description: '🗃️ rc-design is a component library developed for react, providing developers with a more lightweight and concise component library choice. Use tsx to write logic, less to write styles, dumi2 to write documentation sites, and jest+ts-jest+react-testing-library for unit testing.',
                icon: '🎨',
                homepage: 'https://sunny-117.github.io/rc-design/',
                stars: 7,
                tags: ['Design-systems', 'React-components', 'Reactjs'],
            },
            {
                name: 'use-react-core',
                repo: 'Sunny-117/use-react-core',
                description: '📦️ A high-quality & reliable React Hooks library.',
                icon: '🎯',
                stars: 5,
                tags: ['Frontend', 'Hooks', 'Javascript'],
            },
            {
                name: 'react-challenges',
                repo: 'Sunny-117/react-challenges',
                description: 'React 挑战',
                icon: '🌈',
                stars: 4,
            },
            {
                name: 'abtest-kit',
                repo: 'Sunny-117/abtest-kit',
                description: '🔧 轻量级 A/B 测试 SDK，支持多种分流策略和可选的 React 集成。基于 robuild 构建，仅 2.2 kb。',
                icon: '🧪',
                homepage: 'https://sunny-117.github.io/abtest-kit/',
                stars: 2,
                tags: ['Abtest', 'Abtest-framework', 'Abtest-kit'],
            },
            {
                name: 'eslint-plugin-react-boundary',
                repo: 'Sunny-117/eslint-plugin-react-boundary',
                description: 'ESLint plugin to ensure React components are wrapped with Boundary',
                icon: '🔮',
                homepage: 'https://www.npmjs.com/package/eslint-plugin-react-boundary',
                stars: 2,
                tags: ['Boundary', 'Error-boundary', 'Eslint'],
            },
            {
                name: 'eslint-plugin-react-pure-export',
                repo: 'Sunny-117/eslint-plugin-react-pure-export',
                description: 'An ESLint plugin to enforce separation between React components and pure logic modules, improving React Fast Refresh stability and code organization.',
                icon: '🔥',
                stars: 2,
                tags: ['Eslint', 'Eslint-plugin', 'Eslint-rules'],
            }
        ],
    },
    {
        title: 'Vue 生态',
        icon: '🌲',
        projects: [
            {
                name: 'tiny-vue',
                repo: 'Sunny-117/tiny-vue',
                description: 'Vue 3 设计哲学与源码揭秘',
                icon: '💚',
                homepage: 'https://juejin.cn/column/7391745629876830208',
                stars: 10,
                tags: ['Components', 'Tutorial-code', 'Vuejs'],
            },
            {
                name: 'network-speed-js',
                repo: 'Sunny-117/network-speed-js',
                description: 'A small tool for testing network speed. It also has the ability to test internal and external networks.',
                icon: '📡',
                stars: 4,
                tags: ['Javascript', 'Network-analysis', 'Sdk-js'],
            },
            {
                name: 'vue-challenges',
                repo: 'Sunny-117/vue-challenges',
                description: 'vue-challenges',
                icon: '🎭',
                stars: 2,
            },
            {
                name: 'Sunny-117.github.io',
                repo: 'Sunny-117/Sunny-117.github.io',
                description: 'Sunny-117.github.io',
                icon: '💥',
                stars: 0,
            }
        ],
    },
    {
        title: '工具库 & SDK',
        icon: '📦',
        projects: [
            {
                name: 'lodash-ts',
                repo: 'Sunny-117/lodash-ts',
                description: '🎉 A consistent, modular, and performant JavaScript utility library.',
                icon: '🔨',
                stars: 17,
                tags: ['Javascript', 'Lodash', 'Rollup'],
            },
            {
                name: 'browser-storage-lru-cleaner',
                repo: 'Sunny-117/browser-storage-lru-cleaner',
                description: '🧹 A browser storage auto-cleanup SDK utilizing the LRU, supporting both localStorage and IndexedDB, implemented via the Proxy pattern for business logic-agnostic automatic storage eviction  一个基于LRU算法的浏览器存储自动清理SDK，支持localStorage和IndexedDB，通过代理模式实现业务无感知的自动清理。',
                icon: '🗄️',
                homepage: 'https://sunny-117.github.io/browser-storage-lru-cleaner/',
                stars: 4,
                tags: ['Browser', 'Cache', 'Cleanup'],
            },
            {
                name: 'text-processor',
                repo: 'Sunny-117/text-processor',
                description: 'Rust-based text processor provides flexible and efficient processing and conversion of text',
                icon: '🎬',
                stars: 3,
                tags: ['Processor', 'Rust', 'Text'],
            },
            {
                name: 'async-processor',
                repo: 'Sunny-117/async-processor',
                description: '一个轻量级、高性能的异步处理工具库，用于优化 JavaScript 中的异步操作。A lightweight, high-performance asynchronous utility library for optimizing asynchronous operations in JavaScript.',
                icon: '⚙️',
                homepage: 'https://github.com/Sunny-117/async-processor#-async-processor',
                stars: 2,
                tags: ['Async', 'Cache', 'Ioc'],
            },
            {
                name: 'doc-render-sdk',
                repo: 'Sunny-117/doc-render-sdk',
                description: '📝 基于 Vite + robuild + React 的组件文档站点的 SDK',
                icon: '📄',
                stars: 1,
                tags: ['Doc-render', 'Docs', 'Docs-as-code'],
            }
        ],
    },
    {
        title: '编译器 & 转换工具',
        icon: '🔨',
        projects: [
            {
                name: 'tiny-compiler',
                repo: 'Sunny-117/tiny-compiler',
                description: '实现超级 mini 的编译器 | codegen&compiler 生成代码 | 只需要 200 行代码 | 前端编译原理',
                icon: '🔨',
                homepage: 'https://deepwiki.com/Sunny-117/tiny-compiler',
                stars: 10,
                tags: ['Ast', 'Codegen', 'Compiler'],
            },
            {
                name: 'jsx-compilation',
                repo: 'Sunny-117/jsx-compilation',
                description: '🍻 实现 JSX 语法转成 JS 语法的编译器',
                icon: '🔄',
                homepage: 'https://sunny-117.github.io/jsx-compilation',
                stars: 6,
                tags: ['Ast', 'Code', 'Generation'],
            },
            {
                name: 'oxc-loader',
                repo: 'Sunny-117/oxc-loader',
                description: 'webpack/Rspack loader for Oxc',
                icon: '💥',
                homepage: 'https://deepwiki.com/Sunny-117/oxc-loader',
                stars: 5,
                tags: ['Bundler', 'Loader', 'Loaders'],
            },
            {
                name: 'code-formatter-plugin',
                repo: 'Sunny-117/code-formatter-plugin',
                description: 'AI 代码格式化插件是一个强大的React组件库，专为AI问答场景设计，能够智能识别和渲染流式返回的代码内容。它提供了一套完整的解决方案，包括代码块检测、语法高亮、流式数据模拟和插件化集成能力。',
                icon: '✨',
                homepage: 'https://sunny-117.github.io/code-formatter-plugin/',
                stars: 4,
                tags: ['Ai', 'Code-formatter', 'Detector'],
            },
            {
                name: 'javacompiler',
                repo: 'Sunny-117/javacompiler',
                description: '🧐 一个完整的 Java 编译器实现，支持从源代码到字节码的完整编译流程。',
                icon: '🎮',
                stars: 2,
            },
            {
                name: 'babel-core-plugins',
                repo: 'Sunny-117/babel-core-plugins',
                description: 'an babel plugin that for dev debug',
                icon: '🔌',
                stars: 1,
            }
        ],
    },
    {
        title: '可视化 & 图形',
        icon: '🎨',
        projects: [
            {
                name: 'browser-core',
                repo: 'Sunny-117/browser-core',
                description: '实现最简浏览器渲染模型',
                icon: '🌍',
                stars: 13,
                tags: ['Browser', 'Cpu', 'Effects'],
            },
            {
                name: 'draw-wasm',
                repo: 'Sunny-117/draw-wasm',
                description: '用Wasm实现一个画板',
                icon: '🎯',
                homepage: 'https://rustify-org.github.io/draw-wasm/',
                stars: 7,
                tags: ['Canvas', 'Rust', 'Wasm'],
            },
            {
                name: 'text-image',
                repo: 'Sunny-117/text-image',
                description: '🐛🐛🐛  Text image can \"textify\" text, images, and videos, and can be used with simple configuration 它可以将文字、图片、视频进行「文本化」  只需要通过简单的配置即可使用',
                icon: '🖼️',
                homepage: 'https://sunny-117.github.io/text-image/',
                stars: 2,
                tags: ['Canvas', 'Text-image', 'Textify'],
            },
            {
                name: 'chart',
                repo: 'Sunny-117/chart',
                description: '业务开发常用图表',
                icon: '📊',
                stars: 0,
            }
        ],
    },
    {
        title: '开发工具',
        icon: '🔍',
        projects: [
            {
                name: 'cli',
                repo: 'Sunny-117/cli',
                description: 'cli',
                icon: '⌨️',
                homepage: 'https://juejin.cn/post/7363607004348989479',
                stars: 4,
                tags: ['Cli', 'Core'],
            },
            {
                name: 'esfinder',
                repo: 'Sunny-117/esfinder',
                description: 'esfinder 是一个基于Babel、SWC、Oxc 的用于分析和解析 JavaScript 和 TypeScript 项目中文件的导入及其相关依赖的工具。它能够高效地追踪与导入路径相关的文件，支持静态和动态导入。',
                icon: '🔎',
                stars: 3,
                tags: ['Babel', 'Export', 'Exporter'],
            },
            {
                name: 'startar',
                repo: 'Sunny-117/startar',
                description: '一个用于快速拉取 TypeScript 项目模板的交互式脚手架。通过 startar 你可以在几分钟内选择合适的模板、填写项目信息、初始化 Git 仓库并安装依赖，全流程自动化完成。',
                icon: '⭐',
                stars: 3,
                tags: ['Cli', 'Lib', 'Nodejs'],
            },
            {
                name: 'dev-server-proxy',
                repo: 'Sunny-117/dev-server-proxy',
                description: 'A dynamic proxy middleware for webpack-dev-server that enables hot-swapping proxy configurations and mock data without restarting your dev server. | 为 webpack-dev-server 设计的动态代理中间件，支持无需重启服务即可热更新代理配置和 mock 数据。',
                icon: '🌐',
                homepage: 'https://deepwiki.com/Sunny-117/dev-server-proxy',
                stars: 2,
                tags: ['Dev', 'Dev-server', 'Hot-loader'],
            },
            {
                name: 'commit-genius-js',
                repo: 'Sunny-117/commit-genius-js',
                description: 'Commit Genius 是一个简单的命令行工具，它会读取你暂存区（staged）的代码变更，利用 Google Gemini AI 模型自动生成一条符合 Conventional Commits 规范的提交信息。 🌟 功能亮点 全自动分析：自动读取 git diff --staged 的内容，无需手动复制粘贴。',
                icon: '💡',
                stars: 0,
            }
        ],
    },
    {
        title: 'Rust 项目',
        icon: '🦀',
        projects: [
            {
                name: 'mini-rspack',
                repo: 'Sunny-117/mini-rspack',
                description: '🚀 A simplified webpack bundler using Rust. High-performance JavaScript bundling with Rust and Node.js  一个基于Rust的简化版Webpack打包器。采用Rust实现高性能JavaScript Bundler',
                icon: '🔮',
                homepage: 'https://sunny-117.github.io/mini-rspack/',
                stars: 8,
                tags: ['Bundler', 'High-performance', 'Javascript'],
            },
            {
                name: 'rsdown',
                repo: 'Sunny-117/rsdown',
                description: '一个高性能的 JavaScript/TypeScript 代码转换器，基于 Rust 和 SWC',
                icon: '⚡',
                homepage: 'https://sunny-117.github.io/rsdown/',
                stars: 6,
                tags: ['Bundler', 'Napi-rs', 'Rust'],
            },
            {
                name: 'chat-rs',
                repo: 'Sunny-117/chat-rs',
                description: 'Rust构建简易实时聊天系统',
                icon: '💬',
                stars: 5,
            },
            {
                name: 'v8-rs',
                repo: 'Sunny-117/v8-rs',
                description: '⚡️ V8-RS 是一个基于 Rust 实现的最小可行版本 JavaScript 引擎，采用 JIT（Just-In-Time）编译技术。该引擎结合了解释执行和编译执行的优势，通过 Ignition 风格的字节码解释器快速启动，并通过 TurboFan 风格的优化编译器提升热点代码的执行性能。',
                icon: '🥇',
                stars: 5,
            },
            {
                name: '30-seconds-of-rs',
                repo: 'Sunny-117/30-seconds-of-rs',
                description: '30 seconds to collect useful rust snippet.',
                icon: '📝',
                stars: 2,
            },
            {
                name: 'monorepo-graph',
                repo: 'Sunny-117/monorepo-graph',
                description: 'Visualize Monorepo dependencies, support multi format output and intelligent analysis; 可视化 monorepo 依赖关系，支持多格式输出和智能分析',
                icon: '🌟',
                homepage: 'https://github.com/Sunny-117/monorepo-graph',
                stars: 2,
                tags: ['Graph', 'Monorepo', 'Monorepo-graph'],
            }
        ],
    },
    {
        title: 'Node.js & 后端',
        icon: '🟢',
        projects: [
            {
                name: 'go100',
                repo: 'Sunny-117/go100',
                description: 'go100',
                icon: '🎖️',
                stars: 1,
            },
            {
                name: 'im',
                repo: 'Sunny-117/im',
                description: 'Instant messaging system by golang',
                icon: '⚙️',
                stars: 1,
            },
            {
                name: 'go-enjoy',
                repo: 'Sunny-117/go-enjoy',
                description: 'go-enjoy',
                icon: '📚',
                stars: 0,
            }
        ],
    },
    {
        title: '桌面应用 & 扩展',
        icon: '💻',
        projects: [
            {
                name: 'electron',
                repo: 'Sunny-117/electron',
                description: '《Electron桌面客户端应用程序开发入门到原理》专栏',
                icon: '⚡',
                homepage: 'https://juejin.cn/column/7400672360453259264',
                stars: 8,
                tags: ['Electron', 'Juejin'],
            }
        ],
    },
    {
        title: 'AI & 机器学习',
        icon: '🤖',
        projects: [
            {
                name: 'AI',
                repo: 'Sunny-117/AI',
                description: 'AI',
                icon: '🧠',
                stars: 2,
            }
        ],
    },
    {
        title: '其他项目',
        icon: '🎮',
        projects: [
            {
                name: 'Sunny-117',
                repo: 'Sunny-117/Sunny-117',
                description: 'Sunny-117',
                icon: '🎖️',
                stars: 18,
            },
            {
                name: 'lite-tracker',
                repo: 'Sunny-117/lite-tracker',
                description: '🍻 前端服务监控原理与手写开源监控框架SDK',
                icon: '🔧',
                homepage: 'https://juejin.cn/spost/7374265502669160482',
                stars: 17,
                tags: ['Monitor', 'Tracker', 'Web'],
            },
            {
                name: 'tiny-rollup',
                repo: 'Sunny-117/tiny-rollup',
                description: '🌱 Featherlight Module Bundler | ⚡ Second-Level Build Speed | 🌳 Intelligent Tree-Shaking  🌱 轻量模块打包器 | ⚡ 秒级构建 | 🌳 智能Tree-Shaking',
                icon: '🎖️',
                homepage: 'http://deepwiki.com/Sunny-117/tiny-rollup',
                stars: 8,
                tags: ['Arcon', 'Ast', 'Bundler'],
            },
            {
                name: 'js-toochain-book',
                repo: 'Sunny-117/js-toochain-book',
                description: '掘金专栏 前端工具链 代码仓库 掘金专栏地址：https://juejin.cn/column/7287224080172302336',
                icon: '🎖️',
                stars: 5,
            },
            {
                name: 'mini-formily',
                repo: 'Sunny-117/mini-formily',
                description: 'mini-formily',
                icon: '🔨',
                stars: 5,
            },
            {
                name: 'rollup-core-plugins',
                repo: 'Sunny-117/rollup-core-plugins',
                description: 'Rollup core and plugins',
                icon: '✨',
                homepage: 'https://juejin.cn/post/7363607004348923943',
                stars: 5,
                tags: ['Bundler', 'Hooks', 'Plugins'],
            },
            {
                name: 'webcontainer-ide',
                repo: 'Sunny-117/webcontainer-ide',
                description: 'WebContainer IDE is a production-ready, browser-based development environment that brings the full power of Node.js to your browser. Built on StackBlitz\'s WebContainer technology, it enables developers to code, build, and preview applications without any server infrastructure.',
                icon: '🎪',
                homepage: 'https://webcontainer-ide.vercel.app',
                stars: 5,
                tags: ['Editor', 'Ide', 'Monaco'],
            },
            {
                name: 'everyday',
                repo: 'Sunny-117/everyday',
                description: '使用 Github Actions 来完成自动创建 issues 任务',
                icon: '⭐',
                stars: 4,
            },
            {
                name: 'outilx',
                repo: 'Sunny-117/outilx',
                description: '前端业务代码工具库，提供模块化、高性能的 JavaScript 实用工具函数。',
                icon: '🎖️',
                homepage: 'https://sunny-117.github.io/outilx/',
                stars: 4,
                tags: ['Oxc', 'Rolldown', 'Rolldown-plugin-dts'],
            },
            {
                name: 'json-visual-diff',
                repo: 'Sunny-117/json-visual-diff',
                description: '一个强大且灵活的 JSON 可视化差异对比 SDK，采用可插拔的渲染器架构设计，支持实时编辑预览和多种扩展类型。',
                icon: '⭐',
                homepage: 'https://sunny-117.github.io/json-visual-diff/',
                stars: 3,
                tags: ['Diff', 'Json', 'Json-diff'],
            },
            {
                name: 'MicroFE',
                repo: 'Sunny-117/MicroFE',
                description: 'MicroFE',
                icon: '🧩',
                stars: 3,
            },
            {
                name: 'QuickNote',
                repo: 'Sunny-117/QuickNote',
                description: '✨ 基于 Rust 的轻量级的 macOS 菜单栏笔记应用，随时记录你的想法。',
                icon: '🏆',
                stars: 3,
                tags: ['Desktop', 'Electron', 'Macos'],
            },
            {
                name: 'rka',
                repo: 'Sunny-117/rka',
                description: 'A component that maintains component state and avoids repeated re-rendering.',
                icon: '🔮',
                stars: 3,
                tags: ['Cache', 'React-keepalive', 'Reactjs'],
            },
            {
                name: 'rspack-circular-dependency-plugin',
                repo: 'Sunny-117/rspack-circular-dependency-plugin',
                description: 'Detect circular dependencies in modules compiled with Rspack',
                icon: '🌟',
                stars: 3,
                tags: ['Bundler', 'Circular-reference', 'Plugin'],
            },
            {
                name: 'streamsight',
                repo: 'Sunny-117/streamsight',
                description: 'StreamSight 是一个基于 rrweb 的用户行为录制与回放系统，采用 Monorepo 架构，支持高效的事件采集、压缩存储和安全回放。',
                icon: '🏆',
                homepage: 'https://deepwiki.com/Sunny-117/streamsight',
                stars: 2,
                tags: ['Record', 'Rrweb', 'Tsup'],
            },
            {
                name: 'ureq',
                repo: 'Sunny-117/ureq',
                description: 'A modern, modular, and extensible HTTP request library for JavaScript/TypeScript applications. Built with a clean architecture that supports multiple HTTP implementations and advanced features like caching, retries, interceptors, and more.',
                icon: '🎉',
                stars: 2,
                tags: ['Axios', 'Cache', 'Fetch'],
            },
            {
                name: 'gono',
                repo: 'Sunny-117/gono',
                description: '⚡️ TypeScript Execute | The easiest way to run TypeScript in Node.js with Rolldown',
                icon: '🔧',
                stars: 1,
                tags: ['Esbuild', 'Esno', 'Execute'],
            },
            {
                name: 'notools',
                repo: 'Sunny-117/notools',
                description: 'Node.js 工具包',
                icon: '💥',
                stars: 1,
                tags: ['Node-toolkit', 'Node-utils', 'Nodejs'],
            },
            {
                name: 'nodemon-rs',
                repo: 'Sunny-117/nodemon-rs',
                description: 'A fast implementation of nodemon in Rust. This tool automatically restarts your Node.js application when file changes are detected.',
                icon: '🎨',
                stars: 0,
                tags: ['Nodejs', 'Nodemon', 'Rust'],
            },
            {
                name: 'oxbuild',
                repo: 'Sunny-117/oxbuild',
                description: 'An ultra fast and easy-to-use TypeScript/JavaScript compiler',
                icon: '🎮',
                stars: 0,
            },
            {
                name: 'pkg',
                repo: 'Sunny-117/pkg',
                description: 'pkg',
                icon: '🌈',
                stars: 0,
            }
        ],
    }
]
